site_name: Thüringen Swingen
site_url: https://wwww.thürswingen.de
site_description: Swing Tanz und Jazz in Thüringen
site_author: Sebastian Schieke
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - attr_list

theme:
  name: material
  font: false
  language: de
  palette:
    primary: brown
  features:

plugins:
  - search
  - tags
  - blog

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://social.tchncs.de/@hopit
