site_name: Thüringen swingen
site_url: https://thürswingen.de
site_description: Swing Tanz, Lindyhop und Jazz in Thüringen
site_author: Sebastian Schieke
repo_url: https://github.com/fbim-genosr/thuerswingende/
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences

theme:
  name: material
  font: false
  language: de
  features:
    - toc.integrate

plugins:
  - search
  - git-revision-date-localized
  - rss
